site_name: OpenFPV
site_description: Інструкції, технічні характеристики та налаштування камер OpenIPC - Runcam VRX, WifiLink, адаптивний лінк і не лише. Все для FPV польотів українською.
site_url: https://openfpv.com.ua
use_directory_urls: true

repo_name: GitHub
repo_url: 

extra_css:
  - css/overrides.css  

extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-WFWC26NZLB
  - js/ga.js
  - js/feedback.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Maxwell456/openipc-docs-ukr
    - icon: fontawesome/solid/globe
      link: https://openfpv.com.ua

open_graph:
    image: images/logo.png
    alt: OpenFPV — Документація та підтримка українською
    description: Покрокові інструкції з налаштування камер OpenIPC, Runcam WifiLink та адаптивного лінку.
    title: Документація OpenFPV українською мовою

markdown_extensions:
  - admonition
  - toc:
      permalink: true
theme:
  name: material
  language: uk
  logo: images/logo.png
  favicon: images/logo1.png
  custom_dir: docs/overrides 

  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.highlight
    - search.suggest
    # navigation.expand 

  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Світла тема
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Темна тема

plugins:
  - meta-descriptions
  - social   
  - search:
      lang:
        - uk
        - en
      separator: '[\s\-]+'

nav:
  - Головна:
      - Про проєкт: index.md
      - Оновлення: update/index.md

  - Перші кроки:
      - Швидкий старт: quick-start.md
      - Перед першим польотом:
          - Налаштування дрона: drone.md
          - Налаштування приймача (VRX): groundstation.md
          - Збірка наземної станції Radxa своїми руками: groundstation-build.md
      - Поширені проблеми: troubleshooting.md
          

  - Конфігурація:
      - Прошивки:
          - Оновлення через Multiconfigurator: firmware.md
          - Прошивка через UART: firmware/uart-flashing.md
      - Телеметрія та OSD:
          - VTXMenu: telemetry/vtx-menu.md
          - 40 MHz режим: telemetry/40mhz.md
          - OSD: telemetry/osd.md
          - Перенесення OSD до GS: telemetry/osd-to-gs.md
      - Adaptive-Link: adaptive-link.md
      - Додаткові налаштування: advanced.md
      
  - Обладнання:
      - Камери і відеотрансмітери (VTX):
          - SigmaStart:
              - SigmaStart SSC338Q: vtx/sigmastar-ssc338q.md
          - Goke:
              - Goke GK7205V200: vtx/goke-gk7205v200.md
              - Goke GK7205V300: vtx/goke-gk7205v300.md                     
          - OpenIPC:
              - Mario AIO: vtx/marioaio.md
              - Thinker Air Unit: vtx/thinkerairunit.md
              - UltraSight: vtx/ultrasight.md
          - Runcam:
              - WifiLink v1: vtx/runcamwifilink.md
              - WifiLink v2: vtx/runcamwifilinkv2.md
          - EMAX:
              - Wyvern Link 100 mW: vtx/emaxwyvern100mw.md
              - Wyvern Link 800 mW: vtx/emaxwyvern800mw.md

      - Приймачі (VRX):
          - Runcam WifiLink RX: vrx/runcamwifilinkreceiver.md
          - OpenIPC Bonnet: vrx/openipcbonnet.md

      - Мережеві карти та драйвери:
          - RTL8812EU: net-cards/rtl8812eu.md
          - RTL8812AU: net-cards/rtl8812au.md
          - RTL8812BU: net-cards/rtl8812bu.md
          - Установка драйверів: net-cards/installation.md

  - Ресурси та сумісність:
      - Сумісність обладнання: compatibility.md
      - Корисні посилання: link.md

copyright: "© 2025 OpenFPV Docs — Все права захищені"
