name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir "mkdocs-material[imaging]" \
            mkdocs-glightbox \
            mkdocs-meta-descriptions-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-minify-plugin

      - name: Build site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
